name: Build, Scan & Sign Docker Image
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-and-scan:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2️⃣ Build Docker image
      - name: Build Docker image
        run: |
          docker build -t my-app:latest .

      # 3️⃣ Scan image with Trivy
      - name: Scan image with Trivy
        uses: aquasecurity/trivy-action@v0.31.0
        with:
          image-ref: 'my-app:latest'
          format: 'table'
          exit-code: 1
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'

      # 4️⃣ Generate SBOM with Syft
      - name: Generate SBOM with Syft
        uses: anchore/syft-action@v0.11.1
        with:
          image: 'my-app:latest'
          output: 'json'

      # 5️⃣ Sign image with Cosign
      - name: Sign Docker image with Cosign
        uses: sigstore/cosign-installer@v2
      - name: Cosign sign image
        env:
          COSIGN_PASSWORD: ${{ secrets.COSIGN_PASSWORD }}
        run: |
          cosign sign docker.io/your-dockerhub-username/my-app:latest